apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-desk
spec:
  selector:
    matchLabels:
      app: service-desk
  replicas: 5
  template:
    metadata:
      labels:
        app: service-desk
    spec:
      containers:
      - name: app
        image: afakharany/servicedesk:mysql.1
        env:
        - name: db_user
          value: "root"
        - name: db_password
          value: "root"
        - name: db_host
          value: "mysql-svc"