apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-desk
spec:
  selector:
    matchLabels:
      app: service-desk
  replicas: 1
  template:
    metadata:
      labels:
        app: service-desk
    spec:
      containers:
      - name: service-desk
        image: afakharany/servicedesk:1.0
        volumeMounts:
          - name: tickets
            mountPath: /app/tickets.json
            subPath: tickets.json
      volumes:
        - name: tickets
          configMap:
            name: tickets      